version: '3.7'
services:
  db:
    image: postgres:12-alpine
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_USER=cta-manager-service
      - POSTGRES_PASSWORD=cta-manager-service
      - POSTGRES_DB=cta-manager-service