server:
  port: 9090
  shutdown: graceful

spring:
  config:
    import:
      - classpath:config-springdoc.yml
      - optional:file:./secrets-local.properties
  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      FAIL_ON_EMPTY_BEANS: false
#  datasource:
#    url: ${database.url}
#    username: ${database.username}
#    password: ${database.password}
#    url: jdbc:h2:file:/data/demo
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
  flyway:
    enabled: true
#  h2:
#    console:
#      enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        batch: Info
        jdbc.core:
          JdbcTemplate: DEBUG
          StatementCreatorUtils: TRACE
    com:
      zaxxer.hikari:
        HikariConfig: DEBUG


#management:
#  endpoints:
#    web:
#      path-mapping:
#        health: health-check

#app:
#  auth:
#    service-shared-secret: ${service.shared.secret}
#    ignore-paths: /docs, /v3/api-docs/**, /swagger-ui/**, /api-docs.yaml
#  rest:
#    template:
#      connect-timeout: 15000
#      read-timeout: 15000




