springdoc:
  api-docs:
    enabled: "${enable.swagger:true}"
    packagesToScan: ""
    show-actuator: true
  swagger-ui:
    enabled: "${springdoc.api-docs.enabled:true}"
    path: /docs
    url: /api-docs.yaml
    disable-swagger-default-url: true