openapi: 3.0.0
info:
  version: 1.0.0
  title: CTA Manager
  description: API para operações no CTA
servers:
  - url: http://localhost:9090/api/v1/
    description: local
  - url: https://cta-{environment}.ssp.ma.gov.br/api/v1/
    variables:
      environment:
        default: api.dev
        enum:
          - api
          - api.dev
          - api.staging
tags:
  - name: Aeronave
paths:
  /fabricante:
    get:
      summary: Buscar todos os fabricantes de aeronave
      operationId: buscarFabricantes
      tags:
        - Aeronave
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fabricante'
    post:
      summary: Salvar um fabricante de aeronave
      operationId: adicionarFabricante
      tags:
        - Aeronave
      requestBody:
        $ref: '#/components/requestBodies/FabricanteBody'
      responses:
        200:
          description: Criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fabricante'
  /fabricante/{id}:
    parameters:
      - name: id
        in: path
        description: ID do Fabricante
        required: true
        schema:
          type: integer
          format: int64
    get:
      tags:
        - Aeronave
      summary: Buscar um fabricante de aeronave por Id
      operationId: buscarFabricantePorId
      responses:
        200:
          description: Fabricante encontrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fabricante'
        404:
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Remover um fabricante de aeronave por Id
      operationId: removerFabricante
      tags:
        - Aeronave
      responses:
        204:
          description: Fabricante removido com sucesso
        404:
          $ref: '#/components/responses/NotFound'

    put:
      summary: Atualizar um fabricante de aeronave
      operationId: atualizarFabricante
      tags:
        - Aeronave
      requestBody:
        $ref: '#/components/requestBodies/FabricanteBody'
      responses:
        200:
          description: Criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fabricante'

        404:
          $ref: '#/components/responses/NotFound'
  /aeronave:
    get:
      summary: Buscar todas as aeronaves
      operationId: buscarAeronaves
      tags:
        - Aeronave
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aeronave'
    post:
      summary: Salvar aeronave
      operationId: salvarAeronave
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aeronave'
      tags:
        - Aeronave
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aeronave'
  /aeronave/{id}:
    parameters:
      - name: id
        in: path
        description: ID da aeronave
        required: true
        schema:
          type: integer
    get:
      tags:
        - Aeronave
      summary: Buscar uma aeronave por Id
      operationId: buscarAeronavePorId
      responses:
        200:
          description: Aeronave encontrado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aeronave'
        404:
          $ref: '#/components/responses/NotFound'
    put:
      summary: Atualizar uma aeronave
      operationId: atualizarAeronave
      tags:
        - Aeronave
      requestBody:
        $ref: '#/components/requestBodies/AeronaveBody'
      responses:
        200:
          description: Criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aeronave'

        404:
          $ref: '#/components/responses/NotFound'
  /aeronave/{id}/horimetro:
    parameters:
      - name: id
        in: path
        description: ID da aeronave
        required: true
        schema:
          type: integer
    post:
      summary: Adicionar horas de voo e manutenção
      operationId: adicionarHoras
      tags:
        - Aeronave
      requestBody:
        $ref: '#/components/requestBodies/HorimetroBody'
      responses:
        200:
          description: Horimetro adicionado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Horimetro'
        404:
          $ref: '#/components/responses/NotFound'
components:
  schemas:
    Fabricante:
      required:
        - nome
      properties:
        id:
          type: integer
          format: int64
          example: 1
        nome:
          type: string
          example: HELIBRÁS
    Aeronave:
      required:
        - marcas
        - apelido
        - modelo
        - numero_serie
        - categoria_registro
      properties:
        id:
          type: integer
          format: int64
          example: 12
        apelido:
          type: string
          example: Águia
        marcas:
          type: string
          example: PP-PIT
        fabricante:
          $ref: '#/components/schemas/Fabricante'
        modelo:
          type: string
          example: AS350B2
        numero_serie:
          type: integer
          example: 4942
        horimetro:
          $ref: '#/components/schemas/Horimetro'
        categoria_registro:
          type: string
          example: SAE
    Error:
      properties:
        code:
          type: string
          example: 404
        message:
          type: string
          example: Valor inválido
      required:
        - code
        - message
    Horimetro:
      properties:
        hora_total:
          type: string
          example: "04:48"
          readOnly: true
        hora_manutencao:
          type: string
          example: "03:12"
          readOnly: true
        hora_total_decimal:
          type: number
          format: double
          example: 4.8
        hora_manutencao_decimal:
          type: number
          format: double
          example: 3.2
    Horimetros:
      type: array
      items:
        $ref: '#/components/schemas/Horimetro'
  requestBodies:
    FabricanteBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Fabricante'
    AeronaveBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Aeronave'
    HorimetroBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Horimetro'
  responses:
    NotFound:
      description: Não encontrado
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InvalidParameter:
      description: Invalid parameter
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'