openapi: 3.0.0
info:
  version: 1.0.0
  title: CTA Manager
  description: API para operações no CTA
servers:
  - url: http://localhost:8080
    description: local
tags:
  - name: Aeronave
paths:
  /aeronaves:
    get:
      summary: Buscar todas as aeronaves
      operationId: buscarAeronaves
      tags:
        - Aeronave
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aeronave'
components:
  schemas:
    Aeronave:
      required:
        - marcas
        - fabricante
      properties:
        id:
          type: integer
          format: int64
        marcas:
          type: string
        fabricante:
          type: string
        modelo:
          type: string
        numero_serie:
          type: string